### PR TITLE
fix Router.Helpers import

### PR DESCRIPTION
**Pull request by jamesnolanverran**

### CODE REVIEW

**Comment by riverrun** [comment]
I think it still should be `Web.Router.Helpers`. I've just updated the Phx installer and tried running it, and it's creating `Web.Router.Helpers`, not `Router.Helpers`.

**Comment by jamesnolanverran** [comment]
Odd, my app can't find the Helpers unless I remove 'Web'.  I thought it was a typo but yeah, reading the comments on Phoenix.Router it looks like it should work. I'll see if I can get it working on a new project

**Comment by jamesnolanverran** [comment]
I still get an error using phoenix 1.3-rc "** (CompileError) lib/temp/web/controllers/authorize.ex:5: module Temp.Web.Router.Helpers is not loaded and could not be found" 

Also I have to adjust my routes to `Web.UserController` and move templates - ex: user templates to 'web/templates/web/user/' before things start working.

**Comment by jamesnolanverran** [comment]
I'm just experimenting btw - nothing pressing. Let me know if I'm doing it wrong or if there's anything I can try to help test etc. :)

**Comment by riverrun** [comment]
I'll keep this open while we discuss it. I just installed the 1.3-rc2, and I'll be testing it today.

**Comment by riverrun** [comment]
Closing this for now. If you have any further issues, let me know.

**Pull request closed without merging**
